name: 'Run Build Image'
description: 'Execute Build Image'

inputs:
  DOCKER_USERNAME:
    description: 'Docker Username'
    required: true
  DOCKER_PASSWORD:
    description: 'Docker Password'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 'Login to Docker Hub'
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}
    
    - name: 'Build Image'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ github.repository.name }}:${{ github.sha.short }}
