name: 'Run Build Image'
description: 'Execute Build Image'

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 'Login to Docker Hub'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_TOKEN }}
    
    - name: 'Build Image'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.CI_REGISTRY }}/${{ secrets.CI_REGISTRY_USER }}/$GITHUB_PROJECT:$GITHUB_SHA
        