name: 'Run Build Image'
description: 'Execute Build Image'

inputs:
  DOCKER_USERNAME:
    description: 'Docker Username'
    required: true
  DOCKER_PASSWORD:
    description: 'Docker Password'
    required: true
  PROJECT_NAME:
    description: 'Project Name'
    required: true
  TAG_VERSION:
    description: 'Tag Version'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 'Login to Docker Hub'
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}
    
    - name: 'Build Image'
      uses: docker/build-push-action@v2
      with:
        DOCKER_USERNAME: ${{ inputs.DOCKER_USERNAME }}
        PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
        TAG_VERSION: ${{ inputs.TAG_VERSION }}
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:${{ inputs.TAG_VERSION }}
