name: 'Run Trivy Scan'
description: 'Execute Trivy Scan'

inputs:
  DOCKER_USERNAME:
    description: 'Docker Username'
    required: true
  DOCKER_PASSWORD:
    description: 'Docker Password'
    required: true
  PROJECT_NAME:
    description: 'Project Name'
    required: true
  TAG_VERSION:
    description: 'Tag Version'
    required: true

runs:
    using: 'composite'
    steps:

      - name: Checkout
        uses: actions/checkout@v2 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.DOCKER_USERNAME }}
          password: ${{ inputs.DOCKER_PASSWORD }}

      - name: 'Install trivy'
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          
      - name: 'Scan Image'
        run: |
          docker pull ${{ inputs.DOCKER_USERNAME }}/${{ inputs.PROJECT_NAME }}:${{ inputs.TAG_VERSION }}
          trivy image --severity HIGH,CRITICAL ${{ inputs.DOCKER_USERNAME }}/${{ inputs.PROJECT_NAME }}:${{ inputs.TAG_VERSION }} --exit-code 1
