name: 'Run Setup'
description: 'Execute Setup for Golang'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: 'Run Setup for Golang'
      run: |
        [ ! -f glide.yml ] || glide install -v
      shell: bash
  